name: Build Docusaurus Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    pull-docs:
        runs-on: ubuntu-latest
        steps:
              - name: Checkout Main Repository
                uses: actions/checkout@v4
                with:
                  submodules: true  # Ensures submodules are initialized
                  fetch-depth: 0
        
              - name: Make fetch_docs.sh Executable
                run: chmod +x ${{ github.workspace }}/scripts/fetch_docs.sh
        
              - name: Fetch All Docs
                run: ${{ github.workspace }}/scripts/fetch_docs.sh

              - name: Debug
                run: | 
                  ls -R ${{ github.workspace }}/MainDocs
                  ls
        
              - name: Upload Docs Artifact
                uses: actions/upload-artifact@v4
                with:
                  name: docs-raw
                  path: ${{ github.workspace }}/MainDocs/docs/

    build:
        runs-on: ubuntu-latest
        needs: pull-docs
        steps:
              - name: Checkout Documentation Repo
                uses: actions/checkout@v4
        
              - name: Download Docs Artifact
                uses: actions/download-artifact@v4
                with:
                  name: docs-raw
                  path: ${{ github.workspace }}/MainDocs/docs/
        
              - name: Install Docusaurus
                run: npm install
                working-directory: ${{ github.workspace }}/MainDocs

              - name: Build Docusaurus Docs
                run: |
                  ls -R ${{ github.workspace }}/MainDocs/docs
                  npm run build -- --config ${{ github.workspace }}/MainDocs/docusaurus.config.js --out-dir ${{ github.workspace }}/MainDocs/docs/build
                  ls -R ${{ github.workspace }}/MainDocs/docs
                working-directory: ${{ github.workspace }}/MainDocs
        
              - name: Package Docs for External Software
                run: |
                  tar -czf ${{ github.workspace }}/built-docs.tar.gz -C ${{ github.workspace }}/MainDocs/docs/build .
        
              - name: Create GitHub Release
                id: create_release
                uses: actions/create-release@v1
                with:
                  tag_name: v1.${{ github.run_number }}
                  release_name: "Docusaurus Docs Build v1.${{ github.run_number }}"
                  body: "Automated release of Docusaurus documentation."
                  draft: false
                  prerelease: false
                env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
              - name: Upload Built Docs to Release
                uses: actions/upload-release-asset@v1
                with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ${{ github.workspace }}/built-docs.tar.gz
                  asset_name: built-docs.tar.gz
                  asset_content_type: application/gzip
                env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            