name: Build Docusaurus Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pull-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Make fetch_docs.sh Executable
        run: chmod +x ${{ github.workspace }}/scripts/fetch_docs.sh

      - name: Fetch All Docs
        run: ${{ github.workspace }}/scripts/fetch_docs.sh

      - name: Debug
        run: | 
          ls -R ${{ github.workspace }}/MainDocs
          ls

  build:
    runs-on: ubuntu-latest
    needs: pull-docs
    steps:
      - name: Checkout Documentation Repo
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t my-docusaurus-image -f dockerfile .
      
      - name: Package Docker Image
        run: docker save my-docusaurus-image -o ${{ github.workspace }}/my-docusaurus-image.tar
  
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: docs-${{ github.run_number }}
          release_name: "Docusaurus Docs Build v1.${{ github.run_number }}"
          body: "Automated release of Docusaurus documentation."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
  
      - name: Upload Docker Image to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/my-docusaurus-image.tar
          asset_name: my-docusaurus-image.tar
          asset_content_type: application/x-tar
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push Docker Image to Docker Hub
        run: docker push my-docusaurus-image

  commit-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
        working-directory: ${{ github.workspace }}/MainDocs

      - name: Check for Changes
        run: |
          git status
          ls -R ${{ github.workspace }}/MainDocs/docs
        working-directory: ${{ github.workspace }}/MainDocs

      - name: Add Changes
        run: git add .
        working-directory: ${{ github.workspace }}/MainDocs

      - name: Commit Changes
        run: |
          git commit -m "Update Docusaurus docs" || echo "No changes to commit"
        working-directory: ${{ github.workspace }}/MainDocs

      - name: Pull Latest Changes
        run: git pull --rebase origin main

      - name: Push Changes
        run: git push origin main
        working-directory: ${{ github.workspace }}/MainDocs
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}