name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pull-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Ensures submodules are initialized
          fetch-depth: 0

      - name: Make fetch_docs.sh Executable
        run: chmod +x ${{ github.workspace }}/scripts/fetch_docs.sh

      - name: Fetch All Docs
        run: ${{ github.workspace }}/scripts/fetch_docs.sh

      - name: Debug
        run: | 
          ls -R ${{ github.workspace }}/MainDocs
          ls

      - name: Upload Docs Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-raw
          path: ${{ github.workspace }}/MainDocs/docs/

  build:
    runs-on: ubuntu-latest
    needs: pull-docs
    steps:
      - name: Checkout Documentation Repo
        uses: actions/checkout@v4

      - name: Download Docs Artifact
        uses: actions/download-artifact@v4
        with:
          name: docs-raw
          path: ${{ github.workspace }}/MainDocs/docs/

      - name: Install Docusaurus
        run: npm install
        working-directory: ${{ github.workspace }}/MainDocs

      - name: Build Docusaurus Docs
        run: |
          ls -R ${{ github.workspace }}/MainDocs/docs
          npm run build -- --config ${{ github.workspace }}/MainDocs/docusaurus.config.js --out-dir ${{ github.workspace }}/MainDocs/docs/build
          ls -R ${{ github.workspace }}/MainDocs/docs
        working-directory: ${{ github.workspace }}/MainDocs

      - name: Upload Built Docs Artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-docs
          path: ${{ github.workspace }}/MainDocs/docs/build

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Built Docs Artifact
        uses: actions/download-artifact@v4
        with:
          name: built-docs
          path: ${{ github.workspace }}/MainDocs/docs/build

      - name: Build Docker Image
        run: |
          docker build -t my-docusaurus-image .

      - name: Save Docker Image
        run: |
          docker save my-docusaurus-image -o ${{ github.workspace }}/docs/my-docusaurus-image.tar

      - name: Load Docker Image
        run: |
          docker load -i ${{ github.workspace }}/docs/my-docusaurus-image.tar

      - name: Publish Docker Image
        run: |
          docker tag my-docusaurus-image my-docker-repo/my-docusaurus-image:latest
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push my-docker-repo/my-docusaurus-image:latest