name: Build Docusaurus Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    pull-docs:
        runs-on: ubuntu-latest
        steps:
              - name: Checkout Main Repository
                uses: actions/checkout@v4
                with:
                  submodules: true  # Ensures submodules are initialized
                  fetch-depth: 0
        
              - name: Make fetch_docs.sh Executable
                run: chmod +x ${{ github.workspace }}/scripts/fetch_docs.sh
        
              - name: Fetch All Docs
                run: ${{ github.workspace }}/scripts/fetch_docs.sh

              - name: Debug
                run: | 
                  ls -R ${{ github.workspace }}/MainDocs
                  ls
        
              - name: Upload Docs Artifact
                uses: actions/upload-artifact@v4
                with:
                  name: docs-raw
                  path: ${{ github.workspace }}/MainDocs/docs/

    build:
        runs-on: ubuntu-latest
        needs: pull-docs
        steps:
              - name: Checkout Documentation Repo
                uses: actions/checkout@v4
        
              - name: Download Docs Artifact
                uses: actions/download-artifact@v4
                with:
                  name: docs-raw
                  path: ${{ github.workspace }}/MainDocs/docs/
        
              - name: Convert Repository Owner to Lowercase
                id: repo_owner_lowercase
                run: echo "::set-output name=repo_owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')"
        
              - name: Build Docker Image
                run: docker build -t ghcr.io/${{ steps.repo_owner_lowercase.outputs.repo_owner }}/docs:${{ github.run_number }} .
                working-directory: ${{ github.workspace }}/MainDocs
        
              - name: Log in to GitHub Container Registry
                uses: docker/login-action@v2
                with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
        
              - name: Push Docker Image
                run: docker push ghcr.io/${{ steps.repo_owner_lowercase.outputs.repo_owner }}/docs:${{ github.run_number }}
        
              - name: Create GitHub Release
                id: create_release
                uses: actions/create-release@v1
                with:
                  tag_name: docs-${{ github.run_number }}
                  release_name: "Docusaurus Docs Build v1.${{ github.run_number }}"
                  body: "Automated release of Docusaurus documentation."
                  draft: false
                  prerelease: false
                env:
                  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
            
              - name: Upload Docker Image to Release
                uses: actions/upload-release-asset@v1
                with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ghcr.io/${{ steps.repo_owner_lowercase.outputs.repo_owner }}/docs:${{ github.run_number }}
                  asset_name: docs-container.tar.gz
                  asset_content_type: application/gzip
                env:
                  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}